name: B2C App CI

on: 
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      E2E: true
      CI: true
      DATABASE_URL: file:./dev.db
      JWT_SECRET: secret
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COURSE_ID: full-stack-development-comp3036-2026

    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PNPM 📦
        uses: pnpm/action-setup@v4
        with:
          version: 10.2.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies 🧪
        run: pnpm install
      - name: Install Playwright Browsers
        working-directory: tests/playwright
        run: pnpm playwright install chromium --with-deps
      - name: Push Database 📦
        run: pnpm --filter @repo/db db:push
      - name: Build the project 🏗
        run: pnpm turbo build --filter=@repo/web
      
      - name: Run tests
        id: test
        uses: WesternSydneyUniversity/autograding-command-grader@v2
        continue-on-error: true
        with: 
          working-directory: tests/playwright
          test-name: "Playwright E2E Tests"
          command: pnpm playwright test
          timeout: 10
          max-score: 1

      - name: Report to Major Assignment
        if: always() # run on failed tests as well
        continue-on-error: true
        uses: tomitrescak/skillpies-reporting@v1.0
        with:
          courseId: ${{env.COURSE_ID}}
          sectionId: major-assignment-in-ci-cd-and-devops
          testResult: ${{steps.test.outputs.result}}